# Generated by Django 4.0.3 on 2022-04-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='postcategory',
            unique_together={('postId', 'categoryId')},
        ),
    ]
