# Generated by Django 4.0.3 on 2022-07-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.category', verbose_name='Categories'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
