# Generated by Django 4.0.3 on 2022-04-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_postcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parentId',
        ),
    ]
