# Generated by Django 4.0.3 on 2022-04-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_category_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
