# Generated by Django 4.0.3 on 2022-04-13 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_category_content_alter_category_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL),
        ),
    ]
