# Generated by Django 4.0.3 on 2022-04-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_image_remove_post_cover_post_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='thumbnail',
        ),
    ]
